name: continuous integration example

on:
    push:
        branches:
            main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1 #taking my code putting it into vm

            - name: Install Java    #install java
              uses: actions/setup-java@v1
              with: 
                java-version: "11"

            - name: Build with gradle!
              working-directory: .
              run: |    #gradlew is a script -> need permisson
                chmod +x gradlew 
                ./gradlew build -x test

            - name: Run tests!!
              run: |    #gradlew is a script -> need permisson
                chmod +x gradlew 
                ./gradlew test
                
