# name: continuous integration example

# on:
#     push:
#         branches:
#             main

# jobs:
#     build-and-test:
#         runs-on: ubuntu-latest

#         steps:
#             - uses: actions/checkout@v1 #taking my code putting it into vm

#             - name: Install Java    #install java
#               uses: actions/setup-java@v1
#               with: 
#                 java-version: "11"

#             - name: Build with gradle!
#               working-directory: .
#               run: |    #gradlew is a script -> need permisson
#                 chmod +x gradlew 
#                 ./gradlew build -x test

#             - name: Run tests!!
#               run: |    #gradlew is a script -> need permisson
#                 chmod +x gradlew 
#                 ./gradlew test
                

name: "dropwizard-ci-pipeline"


on:
 push:
   branches:
     - main
     - week2


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1


      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11


      - name: Build with gradle
        working-directory: .
        run: ./gradlew build -x test


      - name: Run tests
        working-directory: .
        run: ./gradlew test

  run-system-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v2

      - name: Run docker compose
        working-directory: .
        run: docker-compose up -d --build

      - name : Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - run: pip install pytest requests

      - name: Run system tests
        working-directory: .
        run: |
          pip install pytest
          pytest

      - name: Bring server down
        working-directory: .
        run: docker-compose down

